[package]
name = "libgtp"
version = "0.1.0"
authors = ["Arttaaz <arttaaz@gmail.com>"]
edition = "2018"

[features]
default = ["controller"]
controller = []

[dependencies]
log = "0.4"
scrub_log = "0.2.1"

