[package]
name = "libgtp"
version = "0.1.2"
authors = ["Arttaaz <arttaaz@gmail.com>"]
edition = "2021"
description = "A library implmenting the gtp protocol"
license-file = "LICENSE"

[features]
default = ["controller"]
controller = []

[dependencies]
log = "0.4"
scrub_log = "0.2.1"

